### PR TITLE
OctoPrint 1.4 compatibility

### PR DESCRIPTION
**Pull request by battis**
Kudos to @paulkstelis [for the work on translating the 1.3-compatible plugin into better shape for 1.4](https://github.com/battis/OctoPrint-LDAP/pull/5)!

  - Now using the reworked OctoPrint permissions structure for 1.4
  - LDAP OU groups can be synced to OctoPrint as user groups, to allow for setting group-level permissions.
  - A number of configuration options pertaining to the synced LDAP OU groups have been added, but are not yet accessible through the GUI.
  - A number of prior configuration options have been renamed to reduce confusion with OctoPrint-specific terminology (LDAP OUs, rather than groups, to avoid confusion with OctoPrint groups). This includes migration code to disambiguate the migration from older versions of the plugin's settings.
  - Improved settings GUI, with both tidier, tabbed layout and a bit more inline documentation and guidance.

As always, [issues remain](https://github.com/battis/OctoPrint-LDAP/issues), but no show-stoppers.

### CODE REVIEW

**Review by gillg — COMMENTED** [review]
Hi !
Happy to see your new release to stay compatible 🎉

Just some questions :
I don't understand why you merge a version which target your fork on this repo ? It seems not consistent ? (Feel free to change plugin_author_email ;) but for plugin_url and pip I don't understand)
Do you make new features on your fork or directly on this origin ?

Good job in every cases, it's difficult for me to make changes and test them... I have no more printer neither configured LDAP. 😕

**Comment by battis** [comment]
Ah. It appears that, having opened the pull request, it's just been tracking every change that I've made since I made it. I expect I was somehow sloppy in the pull request (should have picked a specific commit, rather than master... I think.)

No need to update the links in your repo! I had updated them in my fork so that I could get the current version listed in the OctoPrint plugin repository, to make it easier to roll it out quickly across my labs.

I have no real investment in which repo is linked (and it makes sense that yours is the base repo), but [I did _just_ submit the pull request to the plugin registry](https://github.com/OctoPrint/plugins.octoprint.org/pull/603).

**Comment by jneilliii** [comment]
So I'm reviewing the PR to the plugin repo and wondering which repo is the one that's going to be kept maintained? Is it @battis fork or @gillg's original repo? It seems the PR submission was for Seth's.

**Comment by gillg** [comment]
For the PyPi repo it's batis for now. If you want I can upload artifact on my PyPi account or delegate permission to stay consistent... we can discuss about best solution.

**Comment by jneilliii** [comment]
Looking at the plugin it doesn't seem PyPi is a relevant issue because the plugin's software update check is a github release URL to battis's fork. We just want to make sure that the plugin that gets registered to the official OctoPrint Plugin Repo is the one that is going to be actively maintained between the authors. Typically that is the original repo, but if that is not going to be the case here that's no problem. Just want to make sure everyone is aware. It will be battis repo that gets the issue requests, etc.

**Comment by battis** [comment]
Definitely actively maintaining in battis/OctoPrint-LDAP, trying to merge in relevant updates upstream to gillg/OctoPrint-LDAP.

@gillg had given me permissions to merge into his repo a while back, but I think when Microsoft did their big GitHub update this spring, it may have changed the way some permissions worked. In any event, I'm currently blocked from merging into gillg/OctoPrint-LDAP, but definitely actively maintaining.

**Review by gillg — APPROVED** [review]
Great job ! :1st_place_medal:

**Comment by gillg** [comment]
I don't know exactly why... But I needed to approve PR review to unlock your merge permissions. If you know a way to avoid it, I could check :)

**Comment by battis** [comment]
Definitely something changed in permissions this spring. I'll look around and see what I can see. Probably this weekend (he says as though it wasn't going to be Rosh Hashanah and he wasn't married to a rabbi...)

**Pull request merged**
